[project]
name = "super"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "林千里", email = "lincheney@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "altair>=6.3.0",
    "marimo>=0.24.2",
]

[project.scripts]
super = "super:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
